config/routes.rb
Podsadzacz::Application.routes.draw do |map|

  resources :lines do
    resources :timetables
    post :recreate, :on => :collection
  end

  resources :stops

  namespace :search do
    post "results" => "search#results"
    root :to => "search#index"
  end

  match "/admin", :to => "admin/sessions#show", :as => "admin"
  devise_for :admin

  root :to => "map#index"

   match ':controller(/:id(/:action(.:format)))'
end

app/controllers/lines_controller.rb
# encoding: utf-8

require "cgi"

class LinesController < ApplicationController
#  provides :ajax, :js, :json
  respond_to :html, :json

#   if request.html? then 'standard' end 

#  before :ensure_authenticated, :exclude => [:index, :show, :show_by_no]
#  layout :standard
#  cache :index, :show

  def index #(format, active = 'active', type = 'all')

#    @type = type
#    if active == "inactive"
#      @active = false
#    else
#      @active = true
#    end

    @types = {"all"       => "wszystkie",
              "tram"      => "tramwajowe",
              "bus"       => "autobusowe",
              "zonalBus"  => "aglomeracyjne",
              "nightBus"  => "nocne"}

#    repository(@active ? :default : :archive) do
#      lines = case @type
#        when "tram"
#          Line.trams
#        when "bus"
#          Line.buses
#        when "zonalBus"
#          Line.buses.select{|x| x.zonalBus?}
#        when "nightBus"
#          Line.buses.select{|x| x.nightBus?}
#        else
#          Line.all
#      end
#

    @lines = Line.by_dest(:limit => 10,:reduce => true, :group => true, :group_level => 1)['rows']

#    @arr = {}
#    line = nil
#    json.each do |row|
#      if(row['couchrest-type'] == "Line")
#        line = row
#      else(row['couchrest-type'] == "Timetable")
#        @arr[line.no] ||= []
#        @arr[line.no] << [line['_id'], row['hub'], line.direction || "nieznany"]
#        line = nil
#      end
#    end


#     if request.xhr?
#       display @lines, :layout => false
#     else
#      display @lines
# render @lines
#     end

    respond_with @lines
  end

  # GET /lines/:id
  def show #(format, id, date = nil)

    @line = Line.get(params['id'])
    raise NotFound unless @line

    @date =
      if true #date.nil?
        @line.begin_date
      else
        #d = Date.parse(date)
        #raise "Błąd" unless @line.period.include? d
        #d
      end

#    if request.xhr?
#      display @line, :layout => false
#    else
#      display @line
#    end

  end

#  def show_by_no(no, direction, format, date = nil)
#    line = Line.all(:no => no).select{|x| x.direction_name == CGI::unescape(direction) && x.period.include?(date.nil? ? Date.today : Date.parse(date))}.first
#    raise NotFound unless line
#    redirect resource(line, :format => format, :date => date)
#  end

  # GET /lines/new
  def new    
    @line = Line.new
  end

  # GET /lines/recreate/:no
  def recreate

    @routes = []
    @no = params['line']['no']
    @date = params['line']['begin_date']
    routes = Mpk.route(@no, @date)
    dst = "?" # TODO: kierunek linii
    used = []
    i = 1

    routes.each do |route|
      @routes << {}
      route.each_pair do |r, stops|

        stops = stops.sort
        next_stop = stops.shift
        prev_stop = ''
        latest_archived = (Line.latest_archived(@no, next_stop.last).timetables rescue [])
        results = {}

        while stop = next_stop
          next_stop = stops.shift
          next_stop_name = next_stop.last unless next_stop.nil?
          stop_name = stop.last
          selected = []
          selected = latest_archived.map{|x| x.stop}.select{|x| x.name == stop_name}

          if selected.empty?
            all = Stop.search(:name => "^" + stop_name + "$").select{|s| @no.to_i < 100 ? s.trams == true : s.buses == true}
            Merb.logger.info "Brak przystanku " + stop_name + " w bazie danych" if all.empty?
            # Wyberz tylko te przystanki, których następne i proprzednie zgadzają się z bierzącą linią
            if all.size < 2
              selected = all
            else
              selected = all.select{|x| x.print_nextstops.include?(next_stop_name || dst) and x.print_prevstops.include?(prev_stop)}
              # Wybierz tylko te przystanki którch następne i poprzednie nie są poprzednimi lub następnymi
              selected = all.select{|x| not (x.print_nextstops.include?(prev_stop) or x.print_prevstops.include?(next_stop_name || dst))} if selected.empty?
              selected = all if selected.empty?
            end
          end

          prev_stop = stop_name
          results[stop.first] = selected
          i+=1
        end
        @routes.last[r] = results
      end
    end
  end

  # POST /lines
  def create

  end

  def edit(id)
    only_provides :html, :js, :ajax
    @line = Line.get(id) || repository(:archive){ Line.get(id) }
    raise NotFound unless @line

    if request.xhr?
      display @line, :layout => false
    else
      display @line
    end
  end

  def auto_create(line_no, stops, date, format)
    transaction = Line.auto_create line_no, stops, date
    redirect resource(:lines, :format => format), :message => {:notice => "Line was successfully created. " << transaction.inspect}
  end

  def update(id, line, format, polylines = {})
    @line = Line.get(id) || repository(:archive){ Line.get(id) }
    raise NotFound unless @line

    line[:end_date] = nil if line[:end_date].empty?

    unless polylines.blank?
      require 'merb/gmap_polyline/gmap_polyline_encoder.rb'
      encoder = GMapPolylineEncoder.new()

      # Należy usawić run aby był bardziej universalny i szybki
#       run = @line.runs.last / 2
#       while(@line.specialsIndexes.include?(run) or @line.shortersIndexes.include?(run)) do
#         run += 1
#       end

      length = 0
      timetables = @line.timetables.dup

      polylines.each_pair do |stop_id, value|

#         stops = timetables.map{|x| x.stop_id}[key.to_i,2]
#         timetable = timetables.select(:stop_id => key) #timetables[key.to_i]
        i = timetables.map{|x| x.stop_id}.index(stop_id.to_i)
        raise "coś nie tak" unless i
        timetable = timetables.delete_at(i) #timetables[i] # delete_at indeks
        code = (encoder.encode( value[1..-2].split(")(").collect{|x| x.split(", ").collect{|y| y.to_f}}) rescue {})

        polyline = Polyline.first_or_create :beg_id => stop_id, :end_id => (timetable.nextinline.stop_id rescue @line.direction.id)
        polyline.points = code[:points]
        jeden = code[:points]
        polyline.levels = code[:levels]
        polyline.save!

        #Merb.logger.info(jeden + " =? " + polyline.points)
        raise "błąd" if jeden != polyline.points
        @date = @line.begin_date

        avg = timetable.avg_speed(@date)
        timetable.ratio = avg > 0 ? polyline.length / (avg / 60) : 0 # km/h # należy się przyjżeć dlaczego zwraca -1; .abs => workaround
        timetable.save!

        length += polyline.length
      end
      # (nie uaktualnia w trybie html)
       line[:length] = (length * 100).round / 100.0
    end

    if @line.update_attributes(line)
      #if request.xhr?
      #  @date = @line.begin_date
      #  message[:notice] = "Line was successfully updated"
      #  render :show, :layout => false
      #else
        redirect resource(@line, :format => format), :message => {:notice => "Linia zaktualizowana"}
      #end
    else
      #display @line, :edit
      raise "todo"
    end
  end

  def delete(id)
    @line = Line.get(id)
    raise NotFound unless @line
    if @line.destroy
      redirect resource(:lines), :message => {:notice => "Line was successfully destroyed."}
    else
      raise InternalServerError
    end
  end

  def polyline
    raise NotFound unless params['id']
#    respond_with Polyline.by_line( :startkey => [params['id'], 0], :endkey => [params['id'], {}] ).map{|p| p.points}
    @polylines = Polyline.by_line( :startkey => [params['id'], 0], :endkey => [params['id'], {}] ).map{|p| p.points }
    @timetables = Timetable.by_line( :startkey => [params['id'], 0], :endkey => [params['id'], {}] ).map{|p| p['ratio'] }

    @polylines.map!.with_index do |pol,i|
#      pol['ratio'] = @timetables[i]
      [pol, @timetables[i]]
    end

    respond_with @polylines 
  end
end # Lines

app/views/lines/_index.js.haml
:javascript
  function Stage(podsadzacz){
  }

  Stage.prototype.setup = function(){
    $("ul.lines > li > ul > li")
      .bind("mouseenter mouseleave mousedown mouseup", function(){
        $(this).toggleClass("ui-state-default")
      })
      .bind("mousedown mouseup", function(){
        $(this).toggleClass("ui-state-hover")
      })

    $("ul.lines > li")
      .bind("mouseenter mouseleave", function(){
        $(this).toggleClass("ui-state-active")
      })
  }

  Stage.prototype.cleanup = function(){}

app/views/lines/_show.js.haml
:javascript

  function Stage(podsadzacz){
    this.map = podsadzacz.map
    this.polys = []
  }

  Stage.prototype.decodeLine = function(encoded){
    var len = encoded.length;
    var index = 0;
    var array = [];
    var lat = 0;
    var lng = 0;

    while (index < len) {
      var b;
      var shift = 0;
      var result = 0;
      do {
        b = encoded.charCodeAt(index++) - 63;
        result |= (b & 0x1f) << shift;
        shift += 5;
      } while (b >= 0x20);
      var dlat = ((result & 1) ? ~(result >> 1) : (result >> 1));
      lat += dlat;

      shift = 0;
      result = 0;
      do {
        b = encoded.charCodeAt(index++) - 63;
        result |= (b & 0x1f) << shift;
        shift += 5;
      } while (b >= 0x20);
      var dlng = ((result & 1) ? ~(result >> 1) : (result >> 1))
      lng += dlng
      array.push([lat * 1e-5, lng * 1e-5])
    }
    return array
  }

  Stage.prototype.setup = function(){
    var that = this
    $.ajax({
      url: "/lines/#{ @line['_id'] }/polyline",
      dataType: "json",
      success : function(json){
        $.each(json, function(){
          var poly = that.addPolyline( this )
          if(poly)
            that.polys.push(poly)
        })
        var beg = that.polys[0].getPath().getAt(0)
        var end = that.polys[that.polys.length - 1].getPath()
        end = end.getAt(end.getLength() - 1)

        var n,s,e,w
        if(beg.lat() > end.lat()) {
          n = beg.lat()
          s = end.lat()
        } else {
          n = end.lat()
          s = beg.lat()
        }
        if(beg.lng() > end.lng()) {
          e = beg.lng()
          w = end.lng()
        } else {
          e = end.lng()
          w = beg.lng()
        }

        that.map.fitBounds(new google.maps.LatLngBounds(new google.maps.LatLng(s,w), new google.maps.LatLng(n,e)) )
      }
    })
  }

  Stage.prototype.addPolyline = function(poly){

    if(poly[0]){

      return new google.maps.Polyline({
        map: this.map,
        path: this.decodeLine(poly[0].replace(/\\\\/g, "\\")).map(function(arr){ return new google.maps.LatLng(arr[0], arr[1]) }),
        strokeColor: this.color(poly[1]),
        strokeOpacity: 0.6,
        strokeWeight: 5
      })
    }
  }

  Stage.prototype.color = function(ratio){
    var hex, rank = (ratio - 5) / (40 - 5)
    if(rank < 0){
      hex = "#ff0000"
    } else if (rank < 1){
      var red = (Math.round((1-rank)*256)).toString(16)
      if(red < 10) red = "0" + red
      var blue = (Math.round(rank*256)).toString(16)
      if(blue < 10) blue = "0" + blue
      hex = "#" + red + "00" + blue
    } else {
      hex = "#0000ff"
    }
    return hex
  }

  Stage.prototype.cleanup = function(){
    $.each(this.polys, function(){
      this.setMap(null)
    })
  }

app/views/lines/index.html.haml
%h1.ui-widget-header
  = "Linie " + @types[@type].to_s
  - unless @active
    = " (nieaktywne)"

%p#filtr
  %b Filtr:
  - @types.each do |url, type|
    = link_to type, ""
-#    = _link_to type.capitalize, url(:lines, @active ? "active" : "inactive", url), :class => "#{'ui-state-focus' if url == @type}"

%ul.list.lines
  - @lines.each do |lines|
    %li
      -# :title => "#{'Zmieniona' if lines.first.temporary?}"
      %span= lines['key'][0]
      %ul
        - lines['value'].sort.each do |id, destination|
          %li
            -# if line[1].nil?
              .admin= _link_to 'Uzupełnij trasę!', url(:new_line_timetable,line)
            = link_to destination, line_path(id), {:title => "Trasa ??? &#65515; " + destination}

- if current_admin
  %p.admin
    = link_to "Dodaj nową linię", new_line_path
    -#%br/
      = link_to "Sprawdź aktualność rozkładów"

- content_for :script do
  = render :partial => 'index.js'

app/views/lines/new.html.haml
%h1.ui-widget-header Nowa linia

-#= error_messages_for @line

- form_tag(recreate_lines_path) do
  %p
    = label :line, :no, "Numer: "
    = text_field :line, :no
  %p
    = label :line, :begin_date, "Rozkłady jazdy ważne od: "
    = text_field :line, :begin_date, :value => "aktualne"
  %p#submit
    = submit_tag "Odtwórz linię"
    or
    = link_to "Cancel", lines_path

-#
  = check_box :active, :label => 'Linia aktywna?'
  = check_box :temporary, :label => 'Rozkład tymczasowy?'
  %p#submit= submit 'Dodaj'

app/views/lines/recreate.html.haml
= form_tag(lines_path, :method => "put") do
  .table
    - colors = ["#8da2fa", "#9ae51a"]
    - @routes.each_with_index do |line, i|
      - j=-1
      - line.sort.each do |route, all_stops|
        - j+=1
        .tr
          .td
            %b{:style => "color:" + colors[i]}= route + ":"
            %ol
              - all_stops.sort.each do |k, stops|
                %li
                  - if not stops.empty?
                    - if stops.size > 1
                      = select :stop, :name => "stops[" + i.to_s + "][" + j.to_s + "][" + k.to_s + "]", :collection => stops, :value_method => :id, :text_method => :surrounding
                    - else
                      = stops.first.name
                      = hidden_field :value => stops.first.id, :name => "stops[" + i.to_s + "][" + j.to_s + "][" + k.to_s + "]"
                      - if not stops.first.location.blank?
                        %i= ", " + stops.first.location
                  - else
                    %span.red= "Błąd - brak przystanku w bazie"

  %p#submit
    = hidden_field :line_no, :value => @no
    = hidden_field :date, :value => @date
    = submit_tag "Stwórz #{ @routes.size.to_s } linie numer #{ @no }"

  -#%p#navigation
    = _link_to 'Spis linii', url(:lines)
    &raquo;
    = _link_to 'Odtwórz', url(:new_line)

-#= link_to '', url("javascripts/lines/recreate.js"), :id => "scriptLink"

app/views/lines/show.html.haml
#YieldInTable
  .tr
    .td
      .ui-widget-header#lineInfo{:title => "#{'Zmieniona' if @line.temp?}"}
        .tr
          %h1#lineNo{:title => "Linia tramwajowa"}
            =h @line.no
          #lineRoute
            %div
              - if @line.timetables.empty?
                Brak trasy!
                .admin= link_to '(Wyznacz nową trasę)', "url(:new_line_timetable,@line)"
              - else
                %span= @line.timetables.first.stop.name
                %span>= ", #{@line.route},&nbsp;".html_safe 
                %span= @line.direction

      -unless @line.active?
        .ui-widget
          .ui-state-error
            %p.state-error
              %span.ui-icon.ui-icon-alert/
              Ta linia nie jest aktywna

      .table#objDetails
        .tr
          .td
            Przystanki:
          .td
            = @line.timetables.size + 1
        .tr
          .td
            = link_to 'Okres kursów:', @line.gchart(@date)[:okres], :class => 'gchart', :title => "Wzgórza Krzesławickie - Bronowice Nowe: Wykres czasu oczekiwania w zależności od czasu. Dane na dzień 01.01.2009"
          .td
            = @line.okres(@date)
          .td
            min
        .tr
          .td
            Długość trasy:
          .td
            = (@line.length * 10).round / 10.0
          .td
            km
        .tr
          .td
            =link_to 'Czas przejazdu:', @line.gchart(@date)[:time], :class => 'gchart', :title => "Wzgórza Krzesławickie - Bronowice Nowe: Wykres czasu przejazdu od pętli początkowej do końcowej w zależności od czasu, z pominięciem kursów które nie zaczynają lub nie kończą kursów na pętlach. Dane na dzień 01.01.2009"
          .td
            = @line.avg_time(@date)
          .td
            min
        .tr
          .td
            =link_to 'Prędkość średnia:', @line.gchart(@date)[:avg], :class => 'gchart', :title => "Wzgórza Krzesławickie - Bronowice Nowe: Wykres prędkości średniej w zależności od przystanku i czasu. Dane na dzień 01.01.2009"
          .td
            = (@line.length / (@line.avg_time(@date) / 60.0) * 10).round / 10.0 rescue 0
          .td
            km/h
        .tr
          .td
            Podatność na korki:
          .td
            %strong{:title => "Średnio #{@line.rush_percent(@date)}% mniejsza prędkość w godzinach szczytu. Najszybszy kurs: #{@line.thefastest_theslowest(@date)[0]} min. Najwolniejszy kurs: #{@line.thefastest_theslowest(@date)[1]} min."}= @line.rush_percent(@date)
          .td
            \%
      #date-picker
        Dane na dzień:
        %b= @date
        #slider
      %p
        -if @line.opposite
          = link_to 'Pokaż przeciwną linię', line_path(@line.opposite['_id'])
          %br
        -if not @line.stops.empty?
          = link_to 'Pokaż przystanki na trasie', line_timetables_path(@line['_id'])
        -# elsif $admin
          .admin= _link_to 'Wyznacz nową trasę', url(:new_line_timetable, @line)

      -# if session.authenticated?
        %p.admin
          = _link_to 'Edytuj linię', url(:edit_line, @line)
          %br
          -unless @line.active?
            = _link_to 'Usuń', url(:delete_line, @line)
  .tr
    .td
      %p#navigation
        Nawigacja:
        = link_to 'Strona główna', '/'
        &raquo;
        = link_to 'Spis linii', lines_path

- content_for :script do
  = render :partial => 'show.js'