config/routes.rb
Podsadzacz::Application.routes.draw do |map|

  resources :lines do
    resources :timetables
    post :recreate, :on => :collection
  end

  resources :stops

  namespace :search do
    post "results" => "search#results"
    root :to => "search#index"
  end

  match "/admin", :to => "admin/sessions#show", :as => "admin"
  devise_for :admin

  root :to => "map#index"

   match ':controller(/:id(/:action(.:format)))'
end

app/controllers/timetables_controller.rb
# encoding: utf-8

class TimetablesController < ApplicationController

#  only_provides :json

#  cache :index, :show

  def index #(line_id)
#    provides :html, :ajax, :js


    @stops = Stop.by_line(:startkey => [params['line_id']], :endkey => [params['line_id'], {}])

    @line = Line.new @stops.shift
    raise NotFound unless @line

#    @alternate_direction = @line.alternate_direction

  end

  def show #(id)
#    provides :html

    @timetable = Timetable.get params['id'] #Timetable.by_line_stop(:key => [params['line_id'], params['id']], :limit => 1).first 
    raise "NotFound" unless @timetable

    @stops = Stop.by_line(:startkey => [@timetable.line_id], :endkey => [@timetable.line_id, {}])
    @stop = @stops[@timetable.nice]
    @line = Line.new @stops.shift

#    @start = - @timetables.index(@timetable)
    @data = @timetable.to_arr
    @description = @data.delete(:description)
#    @alternate_direction = @line.alternate_direction

#    display @timetable, :layout => "timetable"
    render :layout => 'timetable'
  end

  # Pozwala zmienić przystanek rozkładu
  def update(id, stop_id)
    @timetable = Timetable.get(id)
    raise NotFound unless @timetable
    if @timetable.update_attributes({:stop_id => stop_id})
      render({:stop_id => stop_id}.to_json, :layout => false) #redirect resource(@timetable)
    else
      render "Błąd", :layout => false #display @timetable, :edit
    end
  end

  # Następny rozkład jazy
  def next

  end

  # Najbliższe odjazdy
  # Input: Ilość, Czas
  def departures(n = nil, time = Time.now)
    
  end

  # Zwraca <Hash>: {:day => (0..2), :run => n}
  def next_run_number(id)

    timetable = Timetable.get(id)
    raise NotFound unless timetable
    time = Time.now

    out = {}
    out[:day] = Global.day(time)

    sum = timetable.start * 60
    now = time.hour * 60 + time.min
    timetable.minutes(time).compact.each_with_index do |min, i|
      sum += min
      if sum > now
        out[:run] = i+1
        break
      end
    end

#    out[:run] = timetable.minutes(time)[0..timetable.run_number(time + timetable.nextruns(time, 1)[0] * 60)].compact.size
    display out
  end

#  def stop(stop_id, only = "id,line_id")
#    only_provides :json
#
#    stop = Stop.get(stop_id)
#    raise NotFound unless stop
#    @timetables = stop.timetables #.sort_by{|x| x.line.no}
#
#    display @timetables, :only => only.split(",").map{|x| x.to_sym}, :methods => [:line_no]
#  end
end # Timetables

app/views/timetables/index.html.haml
%h1.ui-widget-header
  Przystanki na lini
  = @line.no
%p
  - unless @stops
    .red Brak Przystanków na trasie!

%ul.list.index_timetables

  -# @timetables.flatten.each do |timetable|
  - @stops.each do |stop|
    %li{:class => "#{'left-margin' if false and timetable.line_id != @line.id}"}
      %span= link_to image_tag("rozklad.png", :title => "Rozkład jazdy", :alt => "R"), line_timetable_path(@line['_id'], stop['_id']), :class => 'timetable', :rel => stop.id
      = link_to stop.name, stop_path(stop['_id']), :rel => stop.id
      -#if session.authenticated?
        .admin= link_to 'Edytuj', timetable_path( timetable), :style => "position:absolute;right:5px;top:0;z-index:1"
  %li= link_to @line['destination'], "stop_path(@line.direction)" 

  -# if @timetables
    - @timetables.each do |timetable|
      %li{:class => "#{'left-margin' if timetable.line_id != @line.id}"}
        %span= link_to image_tag("rozklad.png", :title => "Rozkład jazdy", :alt => "R"), url(:timetable, timetable), :class => 'timetable', :rel => timetable.id
        = _link_to timetable.stop.name, url(:stop, timetable.stop), :rel=>timetable.stop_id
        -if session.authenticated?
          .admin= link_to 'Edytuj', url(:timetable, timetable), :style=>"position:absolute;right:5px;top:0;z-index:1"
    %li= _link_to @line.direction_name, url(:stop, @line.direction)

    - if not @another_destination.empty?
      - @another_destination.each do |timetable|
        %li{:class => 'left-margin'}
          %span= link_to image_tag("rozklad.png", :title => "Rozkład jazdy", :alt => "R"), url(:timetable, timetable), :class => 'timetable', :rel => timetable.id
          = _link_to timetable.stop.name, url(:stop, timetable.stop), :rel=>timetable.stop_id
          -if session.authenticated?
            .admin= link_to 'Edytuj', url(:timetable, timetable), :style=>"position:absolute;right:5px;top:0;z-index:1"
      %li{:class => 'left-margin'}= _link_to @another_destination.last.line.direction_name, url(:stop, @another_destination.last.line.direction)


%p= link_to 'Przeciwny kierunek', line_path(@line.opposite['_id']) if false and @line.opposite
= link_to '&laquo; Powrót do linii', line_path(@line)

app/views/timetables/new.html.haml
%h1
  ="Nowy przystanek na lini #{@line.no}"
  ="(kierunek #{@line.directionName})"

= partial :form, :submit => "Dodaj"

%p#navigation
  Nawigacja:
  = _link_to 'Strona główna', '/'
  &raquo;
  = _link_to 'Spis linii', url(:lines)
  &raquo;
  = _link_to @line.no, url(:line, @line)
  &raquo;
  = _link_to 'Przystanki', url(:line_timetables, @line)

app/views/timetables/show.html.haml
.table#timetable{:rel => @timetable.id}
  .tr
    .td
      .no
        = @line.no
    .td
      .table
        .tr
          .td#stopname
            = @timetable.stop.name
        .tr
          .td#route
            %b Trasa:
            %span.upcase= "#{@stops.first.name},&nbsp;".html_safe
            %span>= @line.route
            %span.upcase= ", " + @line.opposite.stops.first.name rescue nil
  .tr
    .td
      .table
        .tr
          .td
            %ol#stopslist{:start => @start}
              - @stops.each do |stop|
                -# class_name = (t == @timetable ? ['present'] : nil)
                %li{:class => "class_name" , :style => "margin-left: #{"t.level * 15"}px"}
                  = link_to stop.name, line_timetable_path(@line['_id'], stop['_id'])
              - if @alternate_direction
                %li{:style => "margin-left: 15px"}= link_to @alternate_direction.name, url(:timetable, @line.opposite.timetables.first)
              %li= link_to @line.direction_name, url(:timetable, @line.opposite.timetables.select{|x| x.level == 0}.first) rescue nil
    .td
      .table#numbers
        .tr
          - @data.each_pair do |day, val|
            .td
              = day
              .table
                - val.each_with_index do |h, i|
                  .tr
                    .td<= (@timetable.start + i)%24
                    .td<= h.join(" ")
      #mpk
        %p
          Zakłócenia w ruchu powodują zmiany czasów odjazdów.
        %p#description<
          - unless @description.blank?
            = @description.join("<br />")
        %p
          Rozkład ważny od
          %b=@line.begin_date.strftime("%d.%m.%Y") if @line.begin_date
          do
          - if @line.end_date
            %b=@line.end_date.strftime("%d.%m.%Y")
          - else
            odwołania
        %p źródło: MPK Kraków