config/routes.rb
Podsadzacz::Application.routes.draw do |map|

  resources :lines do
    resources :timetables
    post :recreate, :on => :collection
  end

  resources :stops

  namespace :search do
    post "results" => "search#results"
    root :to => "search#index"
  end

  match "/admin", :to => "admin/sessions#show", :as => "admin"
  devise_for :admin

  root :to => "map#index"

   match ':controller(/:id(/:action(.:format)))'
end

app/models/stop.rb
##
# Klasa reprezentująca fizyczny przystanek
class Stop < CouchRestRails::Document
  use_database :podsadzacz

#  has n,      :timetables #, :dependent => :destroy
#  has n,      :lines, :through => :timetables
#  has n,      :polylines, :child_key => [:beg_id]

  property    :id
  property    :name     # String,   :length => (3..50), :message => "Nieprawidłowa nazwa przystanku"
  property    :lat      # Float #,    :precision => 10, :scale => 8, :in => (-90..90),   :message => "Szerokość geograficzna musi zawierać się pomiędzy -90, a 90."
  property    :lng      # Float #,    :precision => 10, :scale => 8, :in => (-180..180), :message => "Długość geograficzna musi zawierać się pomiędzy -180, a 180."
  property    :location # String
  property    :buses    # Boolean,  :default => false
  property    :trams    # Boolean,  :default => false

  timestamps!

  view_by :name, :map =>
    "function(doc){
      if (doc['couchrest-type'] == 'Stop' && (doc.buses || doc.trams)){
        emit(doc.name, doc)
      }
    }"

  view_by :id, :map =>
    "function(doc){
      if (doc['couchrest-type'] == 'Stop'){
        emit(doc.id, doc)
      }
    }"

  view_by :line, :map =>
    "function(doc){
      if (doc['couchrest-type'] == 'Line'){
        emit([doc['_id']], doc)
      }
      if (doc['couchrest-type'] == 'Timetable'){
        emit([doc.line_id, doc.nice], {\"_id\": doc.stop_id, \"next2\": doc.next})
      }
    }"
#  , :reduce =>
#    "function(keys, values, rereduce){
#
#      function decodeLine (encoded) {
#        var len = encoded.length;
#        var index = 0;
#        var array = [];
#        var lat = 0;
#        var lng = 0;
#
#        while (index < len) {
#          var b;
#          var shift = 0;
#          var result = 0;
#          do {
#            b = encoded.charCodeAt(index++) - 63;
#            result |= (b & 0x1f) << shift;
#            shift += 5;
#          } while (b >= 0x20);
#          var dlat = ((result & 1) ? ~(result >> 1) : (result >> 1));
#          lat += dlat;
#
#          shift = 0;
#          result = 0;
#          do {
#            b = encoded.charCodeAt(index++) - 63;
#            result |= (b & 0x1f) << shift;
#            shift += 5;
#          } while (b >= 0x20);
#          var dlng = ((result & 1) ? ~(result >> 1) : (result >> 1));
#          lng += dlng;
#
#          array.push([lat * 1e-5, lng * 1e-5]);
#        }
#
#        return array;
#      }
#
#      function distance(lat1,lon1,lat2,lon2) {
#        var R = 6371;
#        var dLat = (lat2-lat1) * Math.PI / 180;
#        var dLon = (lon2-lon1) * Math.PI / 180;
#        var a = Math.sin(dLat/2) * Math.sin(dLat/2) +
#          Math.cos(lat1 * Math.PI / 180 ) * Math.cos(lat2 * Math.PI / 180 ) *
#          Math.sin(dLon/2) * Math.sin(dLon/2);
#        var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
#        return R * c;
#      }
#
#      if(!rereduce){
#
#        var length = 0
#
#        for(var i=0; i<values.length; i++){
#          var points = decodeLine(values[i].replace(/\\\\/g, '\\'))
#          var prev = points.shift()
#          for(var j=0; j<points.length; j++){
#            length += distance(prev[0], prev[1], points[j][0], points[j][1])
#            prev = points[j]
#          }
#        }
#
#        return length
#
#      } else {
#        return sum(values)
#      }
#    }"

  view_by :updated_at, :map =>
    "function(doc){
      if (doc['couchrest-type'] == 'Stop'){

        var type = 0
        if(doc.buses){
          if(doc.trams){
            type = 3
          } else {
            type = 2
          }
        } else if(doc.trams) {
          type = 1
        }

        emit([doc['updated_at']], {n: doc.name, l: doc.location, lng: doc.lng, lat: doc.lat, t: type})
      }
    }"

#  before :destroy do
#    throw :halt unless timetables.empty?
#  end

#  before :valid? do
#    prec = 10**7
#    self.lat = (self.lat * prec).round.to_f / prec
#    self.lng = (self.lng * prec).round.to_f / prec
#  end
    
#  after :save do
    #log = File.open('/home/wasiutynski/www/mpk/log/stops.log', 'a')
    #log << (self.to_json << ",\n")
    #log.close
#  end

  def lines
    [] #timetables.map{|t| t.line}
  end

  def timetables
    Timetable.by_stop :startkey => [self['_id'], 0], :endkey => [self['_id'], {}]
  end

  ##
  # Output<Array of Stops>: Przystanki z których odjeżdzają tramwaje
  def self.trams
    # all(:order => ["name"]).select{|x| x.tram?}
    all(:trams => true)
  end

  ##
  # Output<Array of Stops>: Przystanki z których odjeżdzają autobusy
  def self.buses
    # all(:order => ["name"]).select{|x| x.bus?}
    all(:buses => true)
  end

  def hub
#    Hub.first(:name => name) || Hub.new(:name => name)
    Stop.by_name(:startkey => name, :endkey => name)
  end

  def opposite
    hub.select{|s| s['_id'] != self['_id']}
  end

  ##
  # Output<Integer>: liczba pojazdów zatrzymujących się na przystanku w danym dniu o danej godzinie
  def vph(date)
    out = 0
    timetables.each do |t|
      out += 60 / t.line.okres(date) unless t.line.okres(date) == 0
    end
    out
  end

  ##
  # Output<Integer>: zasięg jako ilość przystanków do których można bezpośrednio dojechać z danego przystanku
  def range
    lines.map{|x| x.stops}.flatten.uniq.size
  end

  ##
  # Output<Integer>: zasięg w procentach, wszystkich przystanków w bazie danych
  # TODO: stopień penetracji jako argument
  def percent_range
    (range.to_f / Stop.count * 1000).round / 10.0
  end

  ##
  # Output<Array of Stops>: przystanki, bezpośrednio połączone. Tj. kolejne przystanki conajmniej jednej z linii
  def nextstops
#    @nextstops ||= Stop.all :id => (Merb::Cache[:memcached].fetch "Stop:" + id.to_s + ":nextstops" do
      timetables.map{|x| x.nextinline ? x.nextinline.stop : x.line.direction }.uniq.compact
#    end)
  end

  def nextstops_names
#    Merb::Cache[:memcached].fetch "Stop:" + id.to_s + ":nextstops_names" do
      nextstops.map{|x| x.name}.uniq
#    end
  end

  ##
  # Output<String>: lista nazw nextstops, połączona przecinkami
  def print_nextstops
    nextstops_names.empty? ? "brak" : nextstops_names.join(", ")
  end

  ##
  # Output<Array of Stops>: przystanki, bezpośrednio połączone. Tj. poprzednie przystanki conajmniej jednej z linii
  def prevstops
#    @prevstops ||= Stop.all :id => (Merb::Cache[:memcached].fetch "Stop:" + id.to_s + ":prevstops" do
      timetables.map{|x| x.previnline.stop_id rescue nil}.uniq.compact
#    end)
  end

  def prevstops_names
#    Merb::Cache[:memcached].fetch "Stop:" + id.to_s + ":prevstops_names" do
      prevstops.map{|x| x.name}.uniq
#    end
  end

  ##
  # Output<String>: lista nazw prevstops, połączona przecinkami
  def print_prevstops
    prevstops_names.empty? ? "brak" : prevstops_names.join(", ")
  end

  ##
  # Output<String>: nazwy: poprzednich przystanków, bierzącego oraz następnych
  def surrounding
    print_prevstops + " &rarr; " + name + " &rarr; " + print_nextstops
  end

  ##
  # Ta metoda nie powinna istnieć, gdyż w domyślnej tabeli przechowuję tylko aktywne obiekty (linie)
  def _lines
    lines.select{|x| x.active}
#     timetables.map{|x| x.line}
  end

  ##
  # Output<Integer>: typ pojazdów obsługujących przystanek
  # * 0 - przystanek nieczynny
  # * 1 - przystanek tramwajowy
  # * 2 - przystanek autobusowy
  # * 3 - przystanek autobusowo-tramwajowy
  def typ
    if trams and buses
      3
    elsif buses
      2
    elsif trams
      1
    else
      0
    end
  end

  ##
  # Output<Bool>
  # Notice: docelowo dwie bazy dla aktywnych i nieaktywnych
  def active?
    trams or buses
  end

  ##
  # Output<Array>: najbliższe odjazdy
  # Input: liczba najbliższych odjazdów, czas
  def departures(time = Time.new, n = 2)
    out = []
    timetables.each do |t|
      out << {:line => t.line.no ,:timetable => t, :minutes_left => t.nextruns(time, n)}
    end
    out.select{|x| not x[:minutes_left].empty?}.sort_by{|x| x[:minutes_left].first}
  end

  ##
  # Output<Float>: Kąt w stopniach, jako liczba zmiennoprzecinkową z zakresu (0..360), który tworzy równik z odcinkiem łączącym dwa przystanki
  # Input: identyfikator przystanku
  # TODO .round.abs
  # angle = (360 - angle) if angle > 180
#   def angle(stop_id)
#     stop = Stop.get stop_id
#     a = stop.lat - lat
#     b = stop.lng - lng
#     c = Math.sqrt(a**2 + b**2)
#     if(b > 0) # I lub II ćwiartka
#       Math.acos(a/c) / Math::PI*180
#     else # III lub IV ćwiartka
#       (2*Math::PI - Math.acos(a/c)) / Math::PI*180
#     end
#   end

  ##
  # Notice: wyłącznie na potrzeby serializacji json. Dziwne.
  #def linie
  #  timetables.map{|x| {:no => x.line.no, :id => x.id, :line_id => x.line.id} }.sort_by{|x| x[:no]}
  #end

  ##
  # Output: Hash of urls to all mantained charts
  def gchart(date)
#     Merb::Cache[:memcached].fetch "Stop:" + id.to_s + ":gcharts" do


      out = {}

#      GoogleChart::LineChart.new('800x200', "Czas oczekiwania na przystanku: " + name + " (w minutach)", false) do |b|
#
#        start = timetables.map{|x| x.first(date) rescue nil}.compact.min
#        time = start
#
#        i=0
#        data = []                 # Minuty do odjazdu po każdej godzinie
#        while time.hour < 23
#          timetables.each do |t|
#            data << t.nextruns(time).map{|x| x + i*60}
#          end
#          i += 1
#          time += 1.hour
#        end
#
#        data = data.flatten.sort
#        last = 0
#        data.map! do |x|
#          x = x - last
#          last = x + last
#          x
#        end
#
#        b.data "Czas", data
#        b.show_legend = false
#        b.axis :y, :labels => [0, data.max]
#        b.axis :x, :labels => [start, time].map{|x| x.strftime("%H:%M")}
#
#        out[:waiting] = b.to_url #(:chbh=>"a")
#      end unless timetables.empty?
#
#      GoogleChart::Base.new('200x200', 'Przystanek x') do |b|
#        out[:qr_code] = b.to_url(:cht=>"qr", :chl=>"test")
#      end

      out
#     end
  end

end

app/controllers/stops_controller.rb
# encoding: utf-8

class StopsController < ApplicationController

  respond_to :json, :except => :edit
  respond_to :html, :except => :timetables

#  cache :index, :unless => :authenticated?
#  eager_cache :create, :index, :uri => '/all-stops.ajax'
#  eager_cache :delete, :index

#  before :ensure_authenticated, :exclude => [:index, :show, :departures, :search, :search_by_name]

  def index

    @types = {"all" => "wszystkie", "tram" => "tramwajowe", "bus" => "autobusowe"}
#
#    @stops = case type
#      when "bus"
#        Stop.buses
#      when "tram"
#        Stop.trams
#      else
#        Stop.all
#    end

    @stops = if(params['q'])
      Stop.search("by_name", params['q'], :limit => params['limit'] || 20)['rows']
    else
      Stop.by_name(:limit => 0)
    end

    respond_with @stops
  end

  def show

    @timetables = Timetable.by_stop(:startkey => [params[:id]], :endkey => [params[:id], {}])
    raise NotFound unless @stop = Stop.new(@timetables.shift)

    @opp = @stop.opposite
    @all = Stop.count
    @directions = {}
    @unknown = []
    @time = Time.now

    @timetables.each do |timetable|
#      line = timetable.line
      if s = timetable['next'] #|| line.direction
        @directions[s] ||= []
        @directions[s] << timetable
      else # Unknown direction
        @unknown << timetable #line
      end

#      if (s = timetable.alternate_nextinline.stop rescue nil)
#        @directions[s] ||= []
#        @directions[s] << line
#      end
    end

    @directions = @directions.map{|x,y| [Stop.get(x), y.sort_by{|z| z['line']}]}.sort_by{|x,y| y.size}.reverse

    respond_with @stop.only('_id', 'name', 'location', 'lng', 'lat', 'buses', 'trams')
  end

#  def departures(id)
#    only_provides :json
#    @stop = Stop.get(id)
#    raise NotFound unless @stop
#
#    render @stop.departures.map{|x| {:id => x[:timetable].id, :m => x[:minutes_left]}}, :layout => false
#  end

  def new
    @stop = Stop.new
  end

  def edit
    @stop = Stop.get(params[:id])
    raise NotFound unless @stop
  end

  def create

    stop[:lat] = stop[:lat].to_f
    stop[:lng] = stop[:lng].to_f   

    @stop = Stop.new(stop)
    if @stop.save
      flash[:notice] = "Dodano przystanek"
      redirect_to stop_path(@stop)
    else
      flash[:error] = "Stop failed to be created"
      render :new
    end
  end

  def update

    @stop = Stop.get(params['id'])
    raise NotFound unless @stop

    if @stop.update_attributes(params['stop'])
      flash[:notice] = "Zaktualizowano przystanek"
      redirect_to stop_path(@stop['_id']) 
    else
      render @stop, :edit
    end

  end

  def delete(id, format)
    @stop = Stop.get(id)
    raise NotFound unless @stop
    if @stop.destroy
      redirect resource(:stops, :format => format), :message => {:notice => "Usunięto przystanek"}
    else
      raise InternalServerError
    end
  end

  def misplaced(id)
    @stop = Stop.get(id)
    raise NotFound unless @stop
  end

#  def search(q, only = "id,name,location")
#    only_provides :json
#
#    @stops = Stop.search :conditions => [q]
#    render @stops, :only => only.split(",").map{|x| x.to_sym}, :methods => [:print_nextstops]
#  end
#
#  def search_by_name(q, only = "id,name")
#    only_provides :json
#
#    @stops = Stop.all :name => q
#    display @stops #, {:only => only.split(",").map{|x| x.to_sym}, :methods => [:print_nextstops]}
#  end

  def timetables

    @stop = Stop.get(params['id'])
    raise NotFound unless @stop
    @timetables = @stop.timetables.sort_by{|x| x['line']}

    respond_with @timetables.map{ |timetable| timetable.only(* params['only'].blank? ? ["_id", "line", "line_id"] : params['only'].split(",")) }
  end

end # Stops

app/views/stops/_details.html.haml
%h1.ui-widget-header
  - case @stop.typ
    - when 1
      =image_tag 'T.png', :title => "Przystanek tramwajowy"
    - when 2
      =image_tag 'A.png', :title => "Przystanek autobusowy"
    - when 3
      =image_tag 'AT.png', :title => "Przystanek autobusowo-tramwajowy"
  =h @stop.name
  - unless @stop.typ > 0
    = "- przystanek nieczynny"

%b Kierunek:
.fg-buttonset.fg-buttonset-single
  - @directions.each do |stop, timetables|
    = link_to stop.name, stop_path(stop['_id']), :class => "fg-button ui-state-default ui-priority-primary", :title => "połączenia: " + stop.print_nextstops, :rel => stop.id.to_s
    .numbers{:rel => stop.id}
      -# lines.sort_by{|x| x.no}.each do |line|
        = link_to line.no, line_path(line), :class => "fg-button ui-state-default remote", :title => "kierunek: " + line.direction_name
      - timetables.each do |t|
        = link_to t['line'], line_path(t.line_id), :class => "fg-button ui-state-default remote", :title => "kierunek: " #+ line.direction_name
  - unless @unknown.empty?
    = link_to "Nieznany", "#", :class => "fg-button ui-state-default ui-priority-primary", :rel => "-1"
    .numbers{:rel => "-1"}
      - for timetable in @unknown
        = link_to timetable['line'], line_path(timetable.line_id), :class => "fg-button ui-state-default remote", :title => "kierunek: " #+ line.direction_name

- if @opp.size != 0
  %p
    %b Przesiadki:
    - @opp.each do |stop|
      - location = stop.location.empty? ? "" : " (" + stop.location + ")"
      = link_to @opp.size == 1 ? 'przystanek w drugą stronę' : stop.name + location , stop_path(stop['_id']), :title => 'połączenia: ' #+ opposite.print_nextstops

.table#objDetails
  .tr
    .td
      Bezpośredni zasięg:
    .td
      %strong{:title => @stop.range.to_s + " z " + @all.to_s + " przystanków"}= @stop.percent_range
    .td
      \%
  .tr
    .td
      =link_to 'Natężenie ruchu:', @stop.gchart(Date.today)[:waiting], :class => 'gchart', :title => "Bronowice Nowe: Wykres czasu oczekiwania w zależności od czasu. Dane na dzień 01.01.2009"
    .td
      = @stop.vph(@time)
    .td
      %strong{:title => "pojazdów na godzinę"} vph

app/views/stops/_edit.js.haml
:javascript

  function Stage(podsadzacz){
    this.map = podsadzacz.map
    this.lat = $("#stop_lat")
    this.lng = $("#stop_lng")
  }

  Stage.prototype.setup = function(){
    var that = this

    this.marker = new google.maps.Marker({
      position: new google.maps.LatLng(#{ @stop.lat }, #{ @stop.lng }),
      map: that.map,
      title: "#{@stop.name}",
      draggable: true
    })

    google.maps.event.addListener(this.marker, "dragend", function() {
      that.lat.attr("value", this.getPosition().lat())
      that.lng.attr("value", this.getPosition().lng())
    })
  }

  Stage.prototype.cleanup = function(){
    this.marker.setMap(null)
  }

app/views/stops/_form.html.haml
-#= error_messages_for @stop
- form_tag(stop_path(@stop['_id']), :method => "put") do
  %p
    = label :stop, :name, "Nazwa"
    = text_field :stop, :name
  %p
    = label :stop, :location, "Ulica"
    = text_field :stop, :location
  %p
    = label :stop, :lat, "Położenie"
    = text_field :stop, :lat
    = text_field :stop, :lng
  %p#submit
    = submit_tag "submit"
    or
    = link_to "Cancel", stop_path(@stop['_id'])

app/views/stops/_index.js.haml
:javascript
  $("#live_search").autocomplete('search.php', {
    width: 300,
    matchContains: true
  })

-#
  var search = $("#live_search")

  var div = document.createElement("div")
  div.className = "ac_results"

  var results = $(document.createElement("ul"))
  results.attr('id', 'live_results')
  results.prependTo(div)
  $(div).insertAfter(search)

  search.keyup(function(){

    console.log(this.value + ": ")
    var val = this.value
    var db = root.db

    if(val == ""){
      results.empty()
      return
    }

    db.transaction(
      function (transaction) {
        var sql = "SELECT id,name FROM stops WHERE name LIKE '%" + val + "%' GROUP BY name ORDER BY name LIMIT 0, 10"
        transaction.executeSql(sql, [],
          function(transaction, result){
            results.empty()
            for(var i=0; i < result.rows.length; i++) {
              var li = $(document.createElement("li"))
              li.text(result.rows.item(i).name)
              results.append(li)
              console.log( result.rows.item(i).name )
            }

          },
          function(){
            console.log("err")
          }
        )
      }
    )
  })

app/views/stops/_script.js.haml
:javascript
  var map = root.map

  $.jGrowl("Kliknij poniżej, aby zbliżyć widok na przystanek: #{ @stop.name }.<br /><br />Skala: <a href='javascript: map.setZoom(17)'>50m</a> <a href='javascript: map.setZoom(16)'>100m</a> <a href='javascript: map.setZoom(15)'>200m</a>.")
  map.panTo(new google.maps.LatLng(#{ @stop.lng }, #{ @stop.lat }))
  try{ google.maps.event.trigger(root.markers['#{ @stop['_id'] }'], 'click') } catch(e){}


  $("#yield ul.list.timetables > li").click(function(){
    var link = $(this).find("a:first-child")
    console.log(link.attr('href'))
    showTimetable(link.attr('href'))
    // return false
  })

  // $(".fg-button").unbind()
  $(".fg-button:not(.ui-state-disabled)")
    .hover(
      function(){
        $(this).addClass("ui-state-hover")
      },
      function(){
        $(this).removeClass("ui-state-hover")
      }
    )
    .mousedown(function(){
      if($(this).hasClass("ui-state-active")){
        $("#yield").load(this.href)
      }
      else{
        $(this).parents(".fg-buttonset-single:first").find(".fg-button.ui-state-active").removeClass("ui-state-active")
        $(this).addClass("ui-state-active")
        if(!$(this).hasClass("remote")){
          $(".fg-buttonset > .numbers:visible").hide()
          $(".list > li:visible").hide()
          $(".fg-buttonset > .numbers[rel=" + $(this).attr("rel") + "], .list > li[rel=" + $(this).attr("rel") + "]").fadeIn("fast")
        }
      }
    })
    .mouseup(function(){
      if(! $(this).is('.fg-button-toggleable, .fg-buttonset-single .fg-button, .fg-buttonset-multi .fg-button') ){
        $(this).removeClass("ui-state-active")
      }
    })
    .click(function(){
      return false
    })

  $(".fg-buttonset > .fg-button:first").addClass("ui-corner-left ui-state-active")
  $(".fg-buttonset > .fg-button:last").addClass("ui-corner-right")
  $(".fg-buttonset > .fg-button").width(100 / $(".fg-buttonset > .fg-button").length + "%")

  div = document.createElement("div")
  tallest = 0

  $(".fg-buttonset > .fg-button").each(function() {
    thisHeight = $(this).height();
    if(thisHeight > tallest) {
      tallest = thisHeight;
    }
    div.appendChild(this)
  });

  $(".fg-buttonset").prepend(div)
  $(".fg-buttonset > div:first .fg-button").height(tallest);
  $(".fg-buttonset > .numbers:not(:first)").hide()

  function refresh(){
    $.ajax({
      url: "http://localhost:5984/podsadzacz_development/_design/Timetable/_view/by_time",
      data: {limit: 20, startkey: ["#{ @stop['_id'] }", 2, "15:04"]},
      dataType: "jsonp",
      success: function(data){
        console.log(data)
        $("#current_timetables").empty()
        if(data.length == 0){
          $("#current_timetables").hide()
            .prev().hide()
        } else {
          $("#current_timetables").show()
            .prev().show()
          $.each(data, function(i,item){

            var parent = $("#timetable_"+item.id)
            var a = document.createElement("a")
            a.href = "/timetables/"+item.id
            a.innerHTML = $("#timetable_"+ item.id +" > a").attr("rel")
            var ul = document.createElement("ul")

            $.each(item.m, function(j,min){
              date = new Date()
              date.setMinutes(date.getMinutes() + min)
              if((m = date.getMinutes()) < 10) m = "0" + m
              var hour = date.getHours() + ":" + m
              var span = document.createElement("span")
              span.innerHTML = "(" + min + " min.)"
              span.className = "small"
              var li = document.createElement("li")
              li.innerHTML = hour
              li.appendChild(span)
              ul.appendChild(li)
            })

            var li = document.createElement("li")
            li.rel = parent.attr('rel')
            li.title = parent.attr('title')
            li.appendChild(a)
            li.appendChild(ul)
            parent.hide()
            $(li).appendTo($("#current_timetables"))
          });
        }

        if($("#all_timetables li:visible").length == 0){
          $("#all_timetables").hide()
            .prev().hide()
        } else{
          $("#all_timetables").show()
            .prev().show()
        }

        $("ul#current_timetables > li[rel!=" + $(".fg-buttonset > .numbers:first").attr("rel") + "]").hide()
        $("ul#current_timetables > li")
          .click(function(){ showTimetable( $(this).find("a:first").attr("href") ) })
          .bind("mouseenter mouseleave", function(){
            $(this).toggleClass("ui-state-default")
          })
          .bind("mousedown mouseup", function(){
            $(this).toggleClass("ui-state-hover")
            $(this).toggleClass("ui-state-default")
          })
      }
    })
  }

  //refresh()
  //var refreshId = window.setInterval("refresh()", 60000 );

app/views/stops/edit.html.haml
%h1.ui-widget-header Editing stop

= render :partial => "form", :submit => "Zmień"

- content_for :script do
  = render :partial => "edit.js"

app/views/stops/index.html.haml
%h1.ui-widget-header= "Przystanki #{@types[@type]}"

-# if session.authenticated?
  %p.admin
    = _link_to 'Nowy przystanek', url(:new_stop)
%p
  %b Live search:
  = text_field :live, :search

%p#filtr
  %b Pokaż:
  - @types.each do |url, type|
    = link_to type.capitalize, stops_path, :class => "#{'ui-state-focus' if url == @type}"

%ul.list.stops
  - @stops.each do |stop|
    %li
      = link_to stop.name, stop_path(stop['_id']), :title => "Połączenia: " #+ stop.print_nextstops
      %span.location= stop.location

-# if session.authenticated?
  %p.admin
    = link_to 'Nowy przystanek', new_stop_path

- content_for :script do
  = render :partial => 'index.js'

app/views/stops/new.html.haml
%h1 Nowy przystanek

= partial :form, :submit => "Dodaj"

= _link_to '&laquo; Powrót', url(:stops)

= link_to '', url("javascripts/stops/new.js"), :id => "scriptLink"

app/views/stops/show.html.haml
= render :partial => 'details'

%p
  %b Odjazdy
  = "(stan na "
  %span#time= @time.strftime("%H:%M")
  = "):"
  
%ul.list.timetables
  - @stop.departures.each do |dep|
    - if dep[:minutes_left].first >= 0
      %li{:title => "kierunek: " + "dep[:timetable].line.direction_name", :id => "timetable_" + dep[:timetable].id.to_s, :rel => (dep[:timetable].nextinline.stop.id.to_s rescue nil)}
        = link_to dep[:line].to_s, line_timetable_path(dep[:timetable].line_id, dep[:timetable]['_id'])
        %ul
          - dep[:minutes_left].each do |min|
            %li
              %span= (@time + 60*min).strftime("%H:%M")
              %span.small= "(#{min} min.)"
%br/

- if current_admin
  %p.admin= link_to 'Edytuj', edit_stop_path( @stop )

%p#navigation
  Nawigacja:
  = link_to 'Strona główna', '/'
  &raquo;
  = link_to 'Spis przystanków', stops_path

- content_for :script do
  = render :partial => 'show.js'